"""New Migration 2025-11-12_11-29-32

Revision ID: 8ecb469ddd58
Revises: 
Create Date: 2025-11-12 04:29:32.895376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecb469ddd58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('plantation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantation_id'), 'plantation', ['id'], unique=True)
    op.create_table('log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('plantation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=True)
    op.create_table('tree',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flower_status', sa.Boolean(), nullable=True),
    sa.Column('pollination_status', sa.Boolean(), nullable=True),
    sa.Column('plantation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plantation_id'], ['plantation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_id'), 'tree', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_id'), table_name='tree')
    op.drop_table('tree')
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_plantation_id'), table_name='plantation')
    op.drop_table('plantation')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
