"""New Migration 2025-11-13_01-12-52

Revision ID: 948a5301031d
Revises: 8ecb469ddd58
Create Date: 2025-11-12 18:12:54.430312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948a5301031d'
down_revision: Union[str, Sequence[str], None] = '8ecb469ddd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('tree', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'longitude')
    op.drop_column('tree', 'latitude')
    # ### end Alembic commands ###
